services:
  postgres:
    container_name: ash-db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      ash-net:

  server:
    container_name: ash-backend
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./apps/ash-qrb-server/.env.prod
    ports:
      - "3000:3000"
    networks:
      ash-net:

  frontend:
    container_name: ash-frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    depends_on:
      - server
    env_file:
      - ./apps/ash-client/.env.prod
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - DNS_TOKEN=${DNS_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - ash-net

  tunnel:
    container_name: ash-client-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - frontend
    networks:
      - ash-net

volumes:
  postgres_data:

networks:
  ash-net: