version: '3.8'
services:
  postgres:
    container_name: ash-db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      ash-net:

  server:
    container_name: ash-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./apps/ash-qrb-server/.env
    ports:
      - 3000:3000
    networks:
      ash-net:

volumes:
  postgres_data:

networks:
  ash-net: { }