services:
  postgres:
    container_name: ash-qrb-server-postgres
    image: postgres:latest
    shm_size: 128mb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: 'trust'  #      only for develop
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      local:

volumes:
  postgres_data:

networks:
  local: { }
  external: {}