version: "3.8"

services:
  elysia-app:
    build:
      context: .
      dockerfile: ./docker/elysia/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elysia-demo-app.rule=Host(`api.ash-qrb.site`)"
      - "traefik.http.services.elysia-demo-app.loadbalancer.server.port=3000"
    networks:
      - web
    expose:
      - "3000"

  traefik:
    image: "traefik:3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web: