version: '3.8'
services:
  postgres:
    container_name: ash-db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      ash-net:

  server:
    container_name: ash-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./apps/ash-qrb-server/.env.prod
    ports:
      - 3000:3000
    networks:
      ash-net:

  frontend:
    container_name: ash-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - server
    env_file:
      - ./apps/ash-client/.env.prod
    ports:
      - 4000:4000

volumes:
  postgres_data:

networks:
  ash-net: { }