[build.base]
  publish = "./client/.next"
  command = "./server/scripts/build.sh && cd client && bun run build"

[functions]
  directory = "./server/dist"

[build.environment]
  # disable NPM install
  NPM_FLAGS = "--version"