[build]
  command = "set -e && curl -fsSL https://bun.sh/install | bash && export PATH='/opt/buildhome/.bun/bin:$PATH' && cd ./server/ && bun install && bun --bun run build"

[build]
  publish = "./client/.next"
  command = "cd ./client && bun install && bun run build"

[functions]
  directory = "./server/dist"

[build.environment]
  # disable NPM install
  NPM_FLAGS = "--version"