[build]
  base = "./packages/ash-qrb-server"
  functions = "netlify/functions"
  # custom build command that install bun and run build
  command = "./scripts/build.sh"
  # vite output folder
  publish = "dist"

[build.environment]
  # disable NPM install
  NPM_FLAGS = "--version"