import type { Metadata } from "next";
import type { AppProps } from 'next/app'
import { Inter } from "next/font/google";
import "@root/assets/postcss/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default MyApp
